name: Build Re Target
description: Builds a Re build system project

inputs:
  path:
    description: The path to the project
    default: .

  targets:
    description: A space-separated list of targets to build (empty builds all)
    default: ''

  cmdline:
    description: Custom command line options (like --msg-level problems)
    default: ''

  arch:
    description: Build architecture
    default: x64
    
  configuration:
    description: Build configuration
    default: release

  re-executable:
    description: The Re executable to use
    default: re

runs:
  using: 'composite'
  steps:
    - run: ${{ inputs.re-executable }} build --arch ${{ inputs.arch }} --configuration ${{ inputs.configuration }} --path ${{ inputs.path }} ${{ inputs.targets }} ${{ inputs.cmdline }}
      shell: bash
